#
# Github Actions for Serverless Framework
#
# Create AWS_KEY and AWS_SECRET secrets in Github repository settings
#
# Master branch will be deployed as DEV and every new tag starting with "v**" (e.g. v1.0, v1.2, v2.0, etc) will be deployed as PROD
#
# Learn more: https://maxkostinevich.com/blog/how-to-deploy-serverless-applications-using-github-actions/
#

name: Deploy Dev
on:
  push:
    branches:
      - master
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
      - name: Install NPM dependencies
        run: yarn
      # Optional
      #- name: Build assets
      #  run: npm run assets-dev
      - name: Deploy Lambda functions
        run: sls deploy -s dev --region af-south-1
    # Optional (to use with serverless-finch serverless plugin)
    #- name: Deploy assets to S3
    #  run: sls client deploy --no-delete-contents --no-confirm -s dev
  publish-schema:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: apollo
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.1.5 | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: 👁️ Introspect subgraph
        run: |
          rover subgraph introspect https://jbq8iau2sk.execute-api.af-south-1.amazonaws.com/dev/graphql | rover subgraph publish United-In-Gaming@current --name lichess --routing-url https://jbq8iau2sk.execute-api.af-south-1.amazonaws.com/dev/graphql --schema -
